// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALEeMluEUywZ4y0Mnp5IFHRKfPvO2CGFM',
    appId: '1:723596201243:web:215f8518ccbac3a06497be',
    messagingSenderId: '723596201243',
    projectId: 'flutterdepi-1433a',
    authDomain: 'flutterdepi-1433a.firebaseapp.com',
    storageBucket: 'flutterdepi-1433a.firebasestorage.app',
    measurementId: 'G-EQ5C5ZC24L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7jSx7-P727TKyD6I4nJTbaOKGxZZHPhE',
    appId: '1:723596201243:android:25c22d16aa3ad1ab6497be',
    messagingSenderId: '723596201243',
    projectId: 'flutterdepi-1433a',
    storageBucket: 'flutterdepi-1433a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsVxgZmqPiS4LogZl-VkVUIg2EtoFW-Q0',
    appId: '1:723596201243:ios:18c38b054ed2e57f6497be',
    messagingSenderId: '723596201243',
    projectId: 'flutterdepi-1433a',
    storageBucket: 'flutterdepi-1433a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsVxgZmqPiS4LogZl-VkVUIg2EtoFW-Q0',
    appId: '1:723596201243:ios:18c38b054ed2e57f6497be',
    messagingSenderId: '723596201243',
    projectId: 'flutterdepi-1433a',
    storageBucket: 'flutterdepi-1433a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALEeMluEUywZ4y0Mnp5IFHRKfPvO2CGFM',
    appId: '1:723596201243:web:55e48e9a03100a646497be',
    messagingSenderId: '723596201243',
    projectId: 'flutterdepi-1433a',
    authDomain: 'flutterdepi-1433a.firebaseapp.com',
    storageBucket: 'flutterdepi-1433a.firebasestorage.app',
    measurementId: 'G-2T5LJB10B9',
  );
}
